@ECHO OFF
CALL clean-cmake-builddir.cmd
SET CLEANERRLVL=%ERRORLEVEL%
IF %CLEANERRLVL% NEQ 0 GOTO CLEANERRORTEST
GOTO CMAKE

:CLEANERRORTEST
IF %CLEANERRLVL% NEQ 1 GOTO CLEANERROR

:CMAKE
CALL run_cmake.bat
IF %ERRORLEVEL% NEQ 0 GOTO CMAKEERROR

CMAKE --build . --clean-first --config MinSizeRel -- /m
IF %ERRORLEVEL% NEQ 0 GOTO BUILDERROR

CMAKE --build . --config MinSizeRel --target PACKAGE
IF %ERRORLEVEL% NEQ 0 GOTO PACKAGEERROR

CMAKE --build . --config MinSizeRel --target INSTALL
IF %ERRORLEVEL% NEQ 0 GOTO INSTALLERROR
GOTO END

:CLEANERROR
ECHO %~n0%~x0: clean error: %CLEANERRLVL%
GOTO END

:CMAKEERROR
ECHO %~n0%~x0: cmake error: %ERRORLEVEL%
GOTO END

:BUILDERROR
ECHO %~n0%~x0: build error: %ERRORLEVEL%
GOTO END

:PACKAGEERROR
ECHO %~n0%~x0: packaging error: %ERRORLEVEL%
GOTO END

:INSTALLERROR
ECHO %~n0%~x0: install error: %ERRORLEVEL%
GOTO END

:END
PAUSE
